import "bootstrap/dist/css/bootstrap.css";
import React from "react";
import "/styles/fontawesome/css/all.css";
import "/styles/roboto/roboto.css";
import "/styles/site.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
